@host = http://192.168.1.13:8080/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3NzI3MTgzMTksImlkIjoiODJiNTQwNjAtNjJiYy00NWFmLTk3N2EtOTgwZjQyZThiMzAzIn0.DRVm2OCMVe0LxDPiwhCQAs8kyiJHGKrZvNjvN1us6xE

GET {{host}}/redagsi-mobile/attendace
Authorization: Bearer {{token}}

### Master data (redagsi-mobile)
GET {{host}}/redagsi-mobile/grade
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/employee-status
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/education
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/marital
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/lesson
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/degree
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/major
Authorization: Bearer {{token}}

GET {{host}}/redagsi-mobile/competency
Authorization: Bearer {{token}}